name       : kpeoplevcard
version    : 0.1
release    : 1
source     :
    - https://cdn.download.kde.org/stable/kpeoplevcard/0.1/kpeoplevcard-0.1.tar.xz : 8de5df5a3abeed2b13fc56f33d1846ae5b90adfc2127bc1b0ffa5e300b7663c3
license    : GPL-2.0-or-later
component  : desktop.kde
summary    : kpeople plugin for vcard
description: |
    Makes it possible to expose vcards to KPeople.
builddeps  :
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
    - kcodecs-devel
    - kconfig-devel
    - kcontacts-devel
    - kcoreaddons-devel
    - ki18n-devel
    - kpeople-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
